#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="arj x86 32 bits"
BROKEN=
FILE=malloc://0x100
IGNORE_ERR=1
ARGS="-b 32"
CMDS='arj
'
EXPECT='{"oeax":0,"eax":0,"ebx":0,"ecx":0,"edx":0,"esi":0,"edi":0,"esp":0,"ebp":0,"eip":0,"eflags":0}
'
run_test

NAME="arj x86 16 bits"
BROKEN=
FILE=malloc://0x100
IGNORE_ERR=1
ARGS="-b 16"
CMDS='arj
'
EXPECT='{"ip":0,"ax":0,"bx":0,"cx":0,"dx":0,"sp":0,"bp":0,"si":0,"di":0,"flags":0}
'
run_test

