.TH ESIL 7
.SH NAME
ESIL  Evaluable Strings Intermediate Language
.SH DESCRIPTION

ESIL aims to describe a Forth-like representation for every target CPU opcode semantics. ESIL representations can be evaluated (interpreted) in order to emulate individual instructions.

.SH SYNTAX

Each command of an ESIL expression is separated by a comma

.IP <source>,<source>,<operation>
.IP <source>,<destination>,<operation>
.IP <source_destination>,<operation>

.SH "SEE ALSO"
.BR radare2 (1)
