.Dd Mar 10, 2017
.Dt R2-DOCKER 1
.Sh NAME
.Nm r2-docker
.Nd Open files within an r2 contained in a Docker image
.Sh SYNOPSIS
.Nm r2-docker
.Op Fl s
.Op Fl u
.Op Fl l
.Op Fl r
.Op Fl d
.Ar file
.Sh DESCRIPTION
radare2 is a commandline hexadecimal editor, and this tool allows you to create a contained version inside a Docker image to open your files safely.
.Pp
The options are:
.Bl -tag -width Fl
.It Fl s
open shell inside the docker image (user r2, pass r2)
.It Fl d
debug program (only for linux-x86-32/64)
.It Fl u
update or create the docker image with r2 inside
.It Fl l
List all docker images with radare2
.It Fl r
Remove the radare2 docker image
.Sh SEE ALSO
.Pp
.Xr radare2(1)
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>
