.Dd Jul 28, 2016
.Dt R2AGENT 1
.Sh NAME
.Nm R2AGENT
.Nd radare2 remoting manager TODO
.Sh SYNOPSIS
.Nm r2agent
.Op Fl adhs
.Op Fl p Ar PORT
.Sh DESCRIPTION
Spawn a server... TODO
.Bl -tag -width Fl
.It Fl a, Cm all
Listen for everyone (localhost by default)
.It Fl d, Cm daemon
Run in daemon mode
.It Fl h, Cm help
Show help prompt
.It Fl s, Cm sandbox
Run in sandbox mode
.It Fl u, Cm httpauth
Enable HTTP Authentification support
.It Fl t, Cm httpauthfile
user:password authentification file
.It Fl p, Cm port Ar PORT
Specify listening port for the agent
.It Fl v
Show version information
.El
.Sh EXAMPLES
.Pp
TODO
.Sh SEE ALSO
.Pp
.Xr radare2(1)
