.Dd Oct 11, 2011
.Dt RADARE2 1
.Os
.Sh NAME
.Nm radare2
.Nd Advanced commandline hexadecimal editor
.Sh SYNOPSIS
.Nm radare2
.Op Fl a Ar arch
.Op Fl b Ar bits
.Op Fl B Ar blocksize
.Op Fl c Ar cmd
.Op Fl e Ar k=v
.Op Fl p Ar project
.Op Fl P Ar patch
.Op Fl s Ar addr
.Op Fl dDwntLV
.Ar file
.Sh DESCRIPTION
radare2 is a commandline hexadecimal editor.
.Pp
"r2" is the alias program name for radare2.
.Pp
This manpage is not updated yet. Feel free to contribute.
.Pp
The options are:
.Bl -tag -width Fl
.It Fl a Ar arch
force asm.arch (x86, ppc, arm, mips, bf, java, ...)
.It Fl b Ar bits
force asm.bits (16, 32, 64)
.It Fl B Ar bsize
Set block size
.It Fl c Ar cmd
Execute the given command before giving prompt
.It Fl e Ar k=v
Set configuration eval variable key=value. For example \-e scr.color=false
.It Fl s Ar addr
Start seeking at this address
.It Fl f
Blocksize = file size
.It Fl d
Start in debugger mode
.It Fl D Ar dbg.backend
Enable debug mode. Set cfg.debug=true
.It Fl w
Open in write mode
.It Fl u
Unknown file size. (Do not limit to file boundaries)
.It Fl n
Do not load r_bin information and ~/.radare2rc
.It Fl t
Get binary information using a thread
.It Fl l Ar plugfile
Load given plugin file
.It Fl L
List supported IO plugins.
.It Fl V
Show version information and exits.
.It Fl h
Show help message
.El
.Sh SHELL
Type '?' for help.
.Pp
.Sh VISUAL
To enter visual mode use the 'V' command. Then press '?' for help.
.Sh DEBUGGER
In r2 the debugger commands are implemented under the 'd' command. Type 'd?' for help.
.Sh ENVIRONMENT
These values can be used from scripts launched from inside radare ('!' command)
.Ar FILE
path to the current working file 
.Sh SEE ALSO
.Pp
.Xr rahash2(1) ,
.Xr rafind2(1) ,
.Xr rabin2(1) ,
.Xr radiff2(1) ,
.Xr ranal2(1) ,
.Xr rasm2(1) ,
.Xr rax2(1) ,
.Xr ragg2(1) ,
.Xr rarun2(1) ,
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>,
nibble <nibble@develsec.org>
