.Dd Sep 30, 2014
.Dt RADARE2 1
.Sh NAME
.Nm radare2
.Nd Advanced commandline hexadecimal editor, disassembler and debugger
.Sh SYNOPSIS
.Nm radare2
.Op Fl a Ar arch
.Op Fl b Ar bits
.Op Fl B Ar baddr
.Op Fl c Ar cmd
.Op Fl e Ar k=v
.Op Fl i Ar file
.Op Fl k Ar kernel
.Op Fl p Ar project
.Op Fl P Ar patch
.Op Fl s Ar addr
.Op Fl 0AdDwntLqv
.Ar -|--|=|file
.Sh DESCRIPTION
radare2 is a commandline hexadecimal editor.
.Pp
"r2" is the alias program name for radare2.
.Pp
This manpage is not updated yet. Feel free to contribute.
.Pp
The options are:
.Bl -tag -width Fl
.It Fl Fl
Open radare2 on an empty file
.It Fl
Equivalent of 'r2 malloc://512'
.It Fl 0
Print \\x00 after initialization and after every command executed
.It Fl a Ar arch
force asm.arch (x86, ppc, arm, mips, bf, java, ...)
.It Fl A
run 'aa' command before prompt or patch to analyze all referenced code
.It Fl b Ar bits
force asm.bits (16, 32, 64)
.It Fl B Ar baddr
Specify the base address to be used when loading a new binary. See 'e?bin.baddr'
.It Fl c Ar cmd
Execute the given command before giving prompt
.It Fl d
Start in debugger mode
.It Fl D Ar dbg.backend
Enable debug mode. Set cfg.debug=true
.It Fl e Ar k=v
Set configuration eval variable key=value. For example \-e scr.color=false
.It Fl f
Blocksize = file size
.It Fl i Ar file
Run script file
.It Fl k Ar kernel
Select kernel (asm.os) for syscall resolution
.It Fl l Ar plugfile
Load given plugin file
.It Fl L
List supported IO plugins.
.It Fl n
Do not load user settings/projects from ~/.radare2rc and ~/.config/radare2/.
.It Fl nn
Only load the rbin structures (elf, mach0, ...)
.It Fl N
Do not perform any analysis (r_bin). Just load the raw file.
.It Fl q
Quiet mode (no prompt)
.It Fl p Ar prj
Set project file
.It Fl P Ar file
Apply rapatch file and quit
.It Fl s Ar addr
Start seeking at this address
.It Fl S
Enable sandboxed mode (same as \-e cfg.sandbox=true)
.It Fl t
Get binary information using a thread
.It Fl v
Show version information and exit.
.It Fl w
Open in write mode
.It Fl h
Show help message
.It Fl H
Show files and environment help
.El
.Sh SHELL
Type '?' for help.
.Pp
.Sh VISUAL
To enter visual mode use the 'V' command. Then press '?' for help.
.Sh DEBUGGER
In r2 the debugger commands are implemented under the 'd' command. Type 'd?' for help.
.Sh ENVIRONMENT
These values can be used from scripts launched from inside radare ('!' command)
.Ar FILE
path to the current working file.
.Sh SEE ALSO
.Pp
.Xr rahash2(1) ,
.Xr rafind2(1) ,
.Xr rabin2(1) ,
.Xr radiff2(1) ,
.Xr rasm2(1) ,
.Xr rax2(1) ,
.Xr ragg2(1) ,
.Xr rarun2(1) ,
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>
