.Dd Sep 30, 2014
.Dt RAHASH2 1
.Sh NAME
.Nm hasher2
.Nd block based hashing utility
.Sh SYNOPSIS
.Nm hasher2
.Op Fl dDheBrkv
.Op Fl a Ar algorithm
.Op Fl b Ar size
.Op Fl s Ar string
.Op Fl i Ar iterations
.Op Fl S Ar seed
.Op Fl f Ar from
.Op Fl t Ar to
.Op [file] ...
.Sh DESCRIPTION
This program is part of the radare project.
.Pp
Hasher allows you to calculate, check and show the hash values of each block of a target file. The block size is 32768 bytes by default. It's allowed to hash from stdin using '-' as a target file.
.Pp
You can hash big files by hashing each block and later determine what part of it has been modified. Useful for filesystem analysis.
.Pp
This command can be used to calculate hashes of a certain part of a file or a command line passed string.
.Pp
This is the command used by the '#' command of radare.
.Bl -tag -width Fl
.It Fl a Ar algo
Select an algorithm for the hashing. Valid values are listed in: rahash2 -L
.It Fl b Ar blocksize
Define the block size
.It Fl d
encoDe base64 string or file
.It Fl D
Decode base64 string or file
.It Fl e
Use little endian to display checksums
.It Fl i Ar iters
Apply the hash Iters times to itself+seed
.It Fl B
Show per-block hash
.It Fl k
Show result using OpenSSH's VisualHostKey randomart algorithm
.It Fl s Ar string
Hash this string instead of using the 'source' and 'hash-file' arguments.
.It Fl S Ar [^]s:string|hexstr
Set seed to hash with, use ^to prefix seed, otherwise its suffixed.
.It Fl f Ar from
Start hashing at given address
.It Fl t Ar to
Stop hashing at given address
.It Fl r
Show output in radare commands
.It Fl v
Show version information
.It Fl h
Show usage help message.
.El
.Sh SEE ALSO
.Pp
.Xr radare2(1) ,
.Xr rafind2(1) ,
.Xr rahash2(1) ,
.Xr rabin2(1) ,
.Xr radiff2(1) ,
.Xr rasm2(1) ,
.Xr ragg2(1) ,
.Xr rarun2(1) ,
.Xr rax2(1) ,
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>
