.Dd Oct 27, 2010
.Dt RANAL2 1
.Os
.Sh NAME
.Nm ranal2
.Nd radare2 code analysis commandline frontend
.Sh SYNOPSIS
.Nm ranal2
.Op -BhL
.Op -o offset
.Op -a arch
.Op -b bits
.Op -l inputlen
.Op [hexpairs|-]
.Sh DESCRIPTION
ranal2 provides a commandline utility to test and perform some code analysis work on a provided hexpair as argument or from stdin if the argument is '-'.
.Pp
.Bl -tag -width Fl
.It Fl B
Input is binary, \-l is mandatory. Useful for stdin
.It Fl o Ar offset
Offset of the opcode to assemble
.It Fl h
Show help message
.It Fl a Ar arch
Set a different architecture (x86, ppc, arm, java)
.It Fl b Ar bits
Specify bit size of registers: 8, 16, 32, 64
.It Fl l Ar len
Specify length of input data
.It Fl L
List all supported code analysis plugins
.It Fl h
Show usage help message
.El
.Sh SEE ALSO
.Pp
.Xr radare2(1) ,
.Xr rafind2(1) ,
.Xr rahash2(1) ,
.Xr rabin2(1) ,
.Xr radiff2(1) ,
.Xr ragg2(1) ,
.Xr rarun2(1) ,
.Xr rasm2(1) ,
.Xr rax2(1) ,
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>,
nibble <nibble@develsec.org>
