.Dd Mar 11, 2010
.Dt RASM2 1
.Os
.Sh NAME
.Nm rasm2
.Nd radare2 patch assembler and disassembler
.Sh SYNOPSIS
.Nm rasm2
.Op Fl dDfBCLev
.Op Fl F Ar in:out
.Op Fl o Ar offset
.Op Fl a Ar arch
.Op Fl b Ar bits
.Op Fl s Ar syntax
.Op Fl l Ar int
.Op ARG
.Sh DESCRIPTION
TODO: This manpage is incomplete.
.Pp
.Bl -tag -width Fl
.It Fl d
Disassemble hexpair bytes. rasm2 \-d 9090
.It Fl D
Disassemble showing hexpair and opcode
.It Fl f
Read data from file instead of ARG.
.It Fl F Ar in:out
Specify input and/or output filters (att2intel, x86.pseudo, ...)
.It Fl o Ar offset
Offset of the opcode to assemble
.It Fl a Ar arch
Set architecture plugin
.It Fl b Ar bits
Set architecture bits
.It Fl s Ar syntax
Select syntax output (intel, att)
.It Fl B
Binary input/output (\-l is mandatory for binary input)
.It Fl l Ar int
Input/Output length
.It Fl C
Output in C format
.It Fl L
List supported asm plugins
.It Fl e
Use big endian
.It Fl h
.El
Show usage help message.
.Sh SEE ALSO
.Pp
.Xr radare2(1) ,
.Xr rafind2(1) ,
.Xr rahash2(1) ,
.Xr rabin2(1) ,
.Xr ranal2(1) ,
.Xr radiff2(1) ,
.Xr ragg2(1) ,
.Xr rarun2(1) ,
.Xr rax2(1) ,
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>,
nibble <nibble@develsec.org>
