.Dd Dec 28, 2020
.Dt RVC2 1
.Sh NAME
.Nm rvc2
.Nd radare version control
.Sh SYNOPSIS
.Nm rvc2
.Op Fl ebBsSvxkKh
.Op [expr] ...
.Sh DESCRIPTION
This command is part of the radare project.
.Pp
Implements a simple version control system that aims to work as frontend for git, as well as its own structure for versioning project changes.
.Pp
This command is pretty new and experimental.
.Sh OPTIONS
.It Fl h
Show usage help message
.It Fl v
Display version
.El
.Sh USAGE
Available variable types are:
.Pp
rvc2 init
echo hello world > README.md
rvc2 add README.md
rvc2 branch
rvc2 commit
.Pp
.Sh SEE ALSO
.Pp
.Xr radare2(1)
.Sh AUTHORS
.Pp
Written by pancake <pancake@nopcode.org>.
