# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/Vector35/binaryninja-api
WRAP_wrap_git_revision:=85faf55c31868f8184a3af34b049a9ac03281490
WRAP_wrap_git_directory:=binaryninja
WRAP_wrap_git_patch_directory:=binaryninja
WRAP_wrap_git_depth:=1

binaryninja_all: binaryninja
	@echo "Nothing to do"

binaryninja:
	git clone --no-checkout --depth=1 https://github.com/Vector35/binaryninja-api binaryninja
	cd binaryninja && git fetch --depth=1 origin 85faf55c31868f8184a3af34b049a9ac03281490
	cd binaryninja && git checkout FETCH_HEAD
	cp -f packagefiles/binaryninja/* binaryninja

binaryninja_clean:
	rm -rf binaryninja
