# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/Vector35/binaryninja-api
WRAP_wrap_git_revision:=c40a5f04deec68d388b2072dc42b29141089f9ce
WRAP_wrap_git_directory:=binaryninja
WRAP_wrap_git_patch_directory:=binaryninja
WRAP_wrap_git_depth:=1

binaryninja_all: binaryninja
	@echo "Nothing to do"

binaryninja:
	git clone --no-checkout --depth=1 https://github.com/Vector35/binaryninja-api binaryninja
	cd binaryninja && git fetch --depth=1 origin c40a5f04deec68d388b2072dc42b29141089f9ce
	cd binaryninja && git checkout FETCH_HEAD
	cp -f packagefiles/binaryninja/* binaryninja

binaryninja_clean:
	rm -rf binaryninja
