# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/capstone-engine/capstone.git
WRAP_wrap_git_revision:=4d90b137b4e75ce4f29d26b9a4cd9fcf2ffa06cd
WRAP_wrap_git_patch_directory:=capstone-v5
WRAP_wrap_git_directory:=capstone-v5
WRAP_wrap_git_diff_files:=capstone-v5/capstone-patches/fix-x86-16.patch
WRAP_wrap_git_depth:=1

.PHONY: capstone-v5_clean capstone-v5_all

capstone-v5:
	if [ ! -d "capstone-v5" -o "4d90b137b4e75ce4f29d26b9a4cd9fcf2ffa06cd" != "$(shell cd capstone-v5 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "capstone-v5"; ${MAKE} capstone-v5_all; fi

capstone-v5_all:
	git clone --no-checkout --depth=1 https://github.com/capstone-engine/capstone.git capstone-v5
	cd capstone-v5 && git fetch --depth=1 origin 4d90b137b4e75ce4f29d26b9a4cd9fcf2ffa06cd
	cd capstone-v5 && git checkout FETCH_HEAD
	cp -rf packagefiles/capstone-v5/* capstone-v5
	for a in capstone-v5/capstone-patches/fix-x86-16.patch ; do echo "patch -d capstone-v5 -p1 < $$a" ; patch -d capstone-v5 -p1 < $$a ; done

capstone-v5_clean:
	rm -rf capstone-v5
