# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/capstone-engine/capstone.git
WRAP_wrap_git_revision:=0a29bf80017b8422c79ba51e3ad5c34ba5ee6142
WRAP_wrap_git_patch_directory:=capstone-next
WRAP_wrap_git_directory:=capstone-next
WRAP_wrap_git_depth:=1

capstone-next_all: capstone-next
	@echo "Nothing to do"

capstone-next:
	git clone --no-checkout --depth=1 https://github.com/capstone-engine/capstone.git capstone-next
	cd capstone-next && git fetch --depth=1 origin 0a29bf80017b8422c79ba51e3ad5c34ba5ee6142
	cd capstone-next && git checkout FETCH_HEAD
	cp -f packagefiles/capstone-next/* capstone-next

capstone-next_clean:
	rm -rf capstone-next
