# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/capstone-engine/capstone.git
# revision = v5
WRAP_wrap_git_revision:=8455b3c5a53b02e524494c7e72a3946a32518170
# patch_directory = capstone-5.0.1
WRAP_wrap_git_directory:=capstone-v5
WRAP_wrap_git_depth:=1

capstone-v5_all: capstone-v5
	@echo "Nothing to do"

capstone-v5:
	git clone --no-checkout --depth=1 https://github.com/capstone-engine/capstone.git capstone-v5
	cd capstone-v5 && git fetch --depth=1 origin 8455b3c5a53b02e524494c7e72a3946a32518170
	cd capstone-v5 && git checkout

capstone-v5_clean:
	rm -rf capstone-v5
