# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/capstone-engine/capstone.git
WRAP_wrap_git_revision:=c66f8774641a3df4f2783b933ca7a50912b56448
WRAP_wrap_git_patch_directory:=capstone-next
WRAP_wrap_git_directory:=capstone-next
WRAP_wrap_git_diff_files:=capstone-next/capstone-patches/fix-x86-16.patch
WRAP_wrap_git_depth:=1

.PHONY: capstone-next_clean capstone-next_all

capstone-next:
	if [ ! -d "capstone-next" -o "c66f8774641a3df4f2783b933ca7a50912b56448" != "$(shell cd capstone-next 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "capstone-next"; ${MAKE} capstone-next_all; fi

capstone-next_all:
	git clone --no-checkout --depth=1 https://github.com/capstone-engine/capstone.git capstone-next
	cd capstone-next && git fetch --depth=1 origin c66f8774641a3df4f2783b933ca7a50912b56448
	cd capstone-next && git checkout FETCH_HEAD
	cp -rf packagefiles/capstone-next/* capstone-next
	for a in capstone-next/capstone-patches/fix-x86-16.patch ; do echo "patch -d capstone-next -p1 < $$a" ; patch -d capstone-next -p1 < $$a ; done

capstone-next_clean:
	rm -rf capstone-next
