# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/trufae/otezip.git
WRAP_wrap_git_revision:=3c21c60040338f440388143fcdc0405563783bf5
# patch_directory = otezip
WRAP_wrap_git_directory:=otezip
WRAP_wrap_git_depth:=1

.PHONY: otezip_clean otezip_all

otezip:
	if [ ! -d "otezip" -o "3c21c60040338f440388143fcdc0405563783bf5" != "$(shell cd otezip 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "otezip"; ${MAKE} otezip_all; fi

otezip_all:
	git clone --no-checkout --depth=1 https://github.com/trufae/otezip.git otezip
	cd otezip && git fetch --depth=1 origin 3c21c60040338f440388143fcdc0405563783bf5
	cd otezip && git checkout FETCH_HEAD

otezip_clean:
	rm -rf otezip
