# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/trufae/otezip.git
WRAP_wrap_git_revision:=51449cff3ad1fc997f76adb8168024eb4d89dcab
# patch_directory = otezip
WRAP_wrap_git_directory:=otezip
WRAP_wrap_git_depth:=1

.PHONY: otezip_clean otezip_all

otezip:
	if [ ! -d "otezip" -o "51449cff3ad1fc997f76adb8168024eb4d89dcab" != "$(shell cd otezip 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "otezip"; ${MAKE} otezip_all; fi

otezip_all:
	git clone --no-checkout --depth=1 https://github.com/trufae/otezip.git otezip
	cd otezip && git fetch --depth=1 origin 51449cff3ad1fc997f76adb8168024eb4d89dcab
	cd otezip && git checkout FETCH_HEAD

otezip_clean:
	rm -rf otezip
