# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/quickjs-ng/quickjs.git
WRAP_wrap_git_revision:=9d15fb60b67c45fd0de413bb49e48f8dacebac16
WRAP_wrap_git_directory:=qjs
WRAP_wrap_git_patch_directory:=qjs
WRAP_wrap_git_depth:=1

.PHONY: qjs_clean qjs_all

qjs:
	if [ ! -d "qjs" ] || ! (cd "qjs" 2>/dev/null && test "$$(git rev-parse HEAD 2>/dev/null)" = "$$(git rev-parse '9d15fb60b67c45fd0de413bb49e48f8dacebac16^{commit}' 2>/dev/null)"); then rm -rf "qjs"; ${MAKE} qjs_all; fi

qjs_all:
	git clone --no-checkout --depth=1 https://github.com/quickjs-ng/quickjs.git qjs
	cd qjs && git fetch --depth=1 origin 9d15fb60b67c45fd0de413bb49e48f8dacebac16
	cd qjs && git checkout FETCH_HEAD
	cp -rf packagefiles/qjs/* qjs

qjs_clean:
	rm -rf qjs
