# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/quickjs-ng/quickjs.git
WRAP_wrap_git_revision:=a3f3bef1cc4522df43f5b55278833565577931fd
WRAP_wrap_git_directory:=qjs
WRAP_wrap_git_patch_directory:=qjs
WRAP_wrap_git_depth:=1

.PHONY: qjs_clean qjs_all

qjs:
	if [ ! -d "qjs" -o "a3f3bef1cc4522df43f5b55278833565577931fd" != "$(shell cd qjs 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "qjs"; ${MAKE} qjs_all; fi

qjs_all:
	git clone --no-checkout --depth=1 https://github.com/quickjs-ng/quickjs.git qjs
	cd qjs && git fetch --depth=1 origin a3f3bef1cc4522df43f5b55278833565577931fd
	cd qjs && git checkout FETCH_HEAD
	cp -rf packagefiles/qjs/* qjs

qjs_clean:
	rm -rf qjs
