# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/quickjs-ng/quickjs
WRAP_wrap_git_revision:=0191aea691e0ae37c35bc6737e73760506876148
WRAP_wrap_git_directory:=qjs
WRAP_wrap_git_patch_directory:=qjs
WRAP_wrap_git_depth:=1

.PHONY: qjs

qjs:
	if [ ! -d "qjs" -o "0191aea691e0ae37c35bc6737e73760506876148" != "$(shell cd qjs && git rev-parse HEAD)" ]; then rm -rf "qjs"; ${MAKE} qjs_all; fi

qjs_all:
	git clone --no-checkout  https://github.com/quickjs-ng/quickjs qjs
	cd qjs && git fetch  origin 0191aea691e0ae37c35bc6737e73760506876148
	cd qjs && git checkout FETCH_HEAD
	cp -rf packagefiles/qjs/* qjs

qjs_clean:
	rm -rf qjs
