# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/radareorg/sdb.git
WRAP_wrap_git_revision:=cc2b1eb67fb3f13659188979e84eed30371dfb9d
WRAP_wrap_git_directory:=sdb
WRAP_wrap_git_depth:=1

.PHONY: sdb_clean sdb_all

sdb:
	if [ ! -d "sdb" -o "cc2b1eb67fb3f13659188979e84eed30371dfb9d" != "$(shell cd sdb 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "sdb"; ${MAKE} sdb_all; fi

sdb_all:
	git clone --no-checkout --depth=1 https://github.com/radareorg/sdb.git sdb
	cd sdb && git fetch --depth=1 origin cc2b1eb67fb3f13659188979e84eed30371dfb9d
	cd sdb && git checkout FETCH_HEAD

sdb_clean:
	rm -rf sdb
