# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/radareorg/vector35-arch-arm64
WRAP_wrap_git_revision:=radare2-2024
WRAP_wrap_git_directory:=v35arm64
WRAP_wrap_git_depth:=1

v35arm64_all: v35arm64
	@echo "Nothing to do"

v35arm64:
	git clone --no-checkout --depth=1 https://github.com/radareorg/vector35-arch-arm64 v35arm64
	cd v35arm64 && git fetch --depth=1 origin radare2-2024
	cd v35arm64 && git checkout

v35arm64_clean:
	rm -rf v35arm64
