# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/nih-at/libzip.git
WRAP_wrap_git_revision:=f30f5290de485348442d168cd7b2eb714d1f20f9
WRAP_wrap_git_directory:=zip
WRAP_wrap_git_patch_directory:=zip
WRAP_wrap_git_depth:=1

.PHONY: zip

zip:
	if [ ! -d "zip" -o "f30f5290de485348442d168cd7b2eb714d1f20f9" != "$(shell cd zip 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "zip"; ${MAKE} zip_all; fi

zip_all:
	git clone --no-checkout --depth=1 https://github.com/nih-at/libzip.git zip
	cd zip && git fetch --depth=1 origin f30f5290de485348442d168cd7b2eb714d1f20f9
	cd zip && git checkout FETCH_HEAD
	cp -rf packagefiles/zip/* zip

zip_clean:
	rm -rf zip
