# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/nih-at/libzip.git
WRAP_wrap_git_revision:=dd450e6ed6faa446518ff6017305b62fd7d55a17
WRAP_wrap_git_directory:=zip
WRAP_wrap_git_patch_directory:=zip
WRAP_wrap_git_depth:=1

.PHONY: zip

zip:
	if [ ! -d "zip" -o "dd450e6ed6faa446518ff6017305b62fd7d55a17" != "$(shell cd zip 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "zip"; ${MAKE} zip_all; fi

zip_all:
	git clone --no-checkout  https://github.com/nih-at/libzip.git zip
	cd zip && git fetch  origin dd450e6ed6faa446518ff6017305b62fd7d55a17
	cd zip && git checkout FETCH_HEAD
	cp -rf packagefiles/zip/* zip

zip_clean:
	rm -rf zip
