# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/madler/zlib.git
WRAP_wrap_git_revision:=51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf
WRAP_wrap_git_directory:=zlib
WRAP_wrap_git_patch_directory:=zlib
WRAP_wrap_git_depth:=1

.PHONY: zlib

zlib:
	if [ ! -d "zlib" -o "51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf" != "$(shell cd zlib 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "zlib"; ${MAKE} zlib_all; fi

zlib_all:
	git clone --no-checkout --depth=1 https://github.com/madler/zlib.git zlib
	cd zlib && git fetch --depth=1 origin 51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf
	cd zlib && git checkout FETCH_HEAD
	cp -rf packagefiles/zlib/* zlib

zlib_clean:
	rm -rf zlib
