# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/zyantific/zydis.git
WRAP_wrap_git_revision:=v4.1.1
WRAP_wrap_git_directory:=zydis
WRAP_wrap_git_depth:=1

.PHONY: zydis zydis_clean zydis_all

zydis:
	if [ ! -d "zydis" -o "v4.1.1" != "$(shell cd zydis 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "zydis"; ${MAKE} zydis_all; fi

zydis_all:
	git clone --no-checkout --depth=1 https://github.com/zyantific/zydis.git zydis
	cd zydis && git fetch --depth=1 origin v4.1.1
	cd zydis && git checkout FETCH_HEAD

zydis_clean:
	rm -rf zydis
