# This file is autogenerated by acr-wrap

WRAP_wrap_file_directory:=zydis-4.1.1
WRAP_wrap_file_source_url:=https://github.com/zyantific/zydis/archive/refs/tags/v4.1.1.tar.gz
WRAP_wrap_file_source_filename:=zydis-v4.1.1.tar.gz
WRAP_wrap_file_source_hash:=943f91eb9ab2a8cc01ab9f8b785e769a273502071e0ee8011cdfcaad93947cec

.PHONY: zydis-4.1.1_clean zydis-4.1.1_all

zydis-4.1.1:
	${MAKE} ${MAKE_FLAGS} zydis-4.1.1_all

zydis-4.1.1_all:
	curl -Lo zydis-v4.1.1.tar.gz https://github.com/zyantific/zydis/archive/refs/tags/v4.1.1.tar.gz
	echo Check 943f91eb9ab2a8cc01ab9f8b785e769a273502071e0ee8011cdfcaad93947cec
	tar xzf zydis-v4.1.1.tar.gz
	cd zydis-4.1.1

zydis-4.1.1_clean:
	rm -rf zydis-4.1.1
