#!/bin/sh
# this r2r.json is generated by r2r which can be taken from the CI. useful to find out which tests are too slow
jq -r 'sort_by(.time_elapsed) | .[] | "\(.time_elapsed) \(.name)"' < /tmp/r2r.json
