#!/bin/sh

shellcheck ./env.sh
shellcheck ./sys/duktape.sh
shellcheck ./sys/android-arm.sh
shellcheck ./sys/dist-bin.sh
shellcheck ./sys/bokken.sh
shellcheck ./sys/install.sh
shellcheck ./sys/emscripten.sh
shellcheck ./sys/build-harden.sh
shellcheck ./sys/dist.sh
shellcheck ./sys/swig.sh
shellcheck ./sys/all.sh
shellcheck ./sys/mingw32-python-deps.sh
shellcheck ./sys/python-dist.sh
shellcheck ./sys/ios-sdk-gcc
shellcheck ./sys/vala.sh
shellcheck ./sys/clone-r2-bindings.sh
shellcheck ./sys/tiny.sh
shellcheck ./sys/mingw32-deps.sh
shellcheck ./sys/install-rev.sh
shellcheck ./sys/uninstall.sh
shellcheck ./sys/maemo.sh
shellcheck ./sys/mingw32-python.sh
shellcheck ./sys/gtkaml.sh
shellcheck ./sys/jam.sh
shellcheck ./sys/android-aarch64.sh
shellcheck ./sys/mingw64-deps.sh
shellcheck ./sys/osx-pkg.sh
shellcheck ./sys/cherrypull.sh
shellcheck ./sys/afl.sh
shellcheck ./sys/python-deps.sh
shellcheck ./sys/android-x86.sh
shellcheck ./sys/lua.sh
shellcheck ./sys/android-shell.sh
shellcheck ./sys/asan.sh
shellcheck ./sys/ndk-gcc
shellcheck ./sys/mingw64.sh
shellcheck ./sys/ios-static.sh
shellcheck ./sys/python-bindist.sh
shellcheck ./sys/full-uninstall.sh
shellcheck ./sys/user.sh
shellcheck ./sys/locdiff
shellcheck ./sys/osx-pkg-uninstall.sh
shellcheck ./sys/whereis.sh
shellcheck ./sys/extras.sh
shellcheck ./sys/android-mips.sh
shellcheck ./sys/valabind.sh
shellcheck ./sys/dist-all.sh
shellcheck ./sys/clang-analyzer.sh
shellcheck ./sys/farm/push.sh
shellcheck ./sys/farm/check.sh
shellcheck ./sys/farm/bins.sh
shellcheck ./sys/farm/prepare.sh
shellcheck ./sys/farm/html.sh
shellcheck ./sys/farm/run.sh
shellcheck ./sys/farm/daemon.sh
shellcheck ./sys/ios-simulator.sh
shellcheck ./sys/android-build.sh
shellcheck ./sys/find-regression.sh
shellcheck ./sys/indent.sh
shellcheck ./sys/farm.sh
shellcheck ./sys/static.sh
shellcheck ./sys/clean.sh
shellcheck ./sys/osx-pkg-uninstall.tool
shellcheck ./sys/mingw32.sh
shellcheck ./sys/ldconfig.sh
shellcheck ./sys/build.sh
shellcheck ./sys/python-r2pipe.sh
shellcheck ./sys/android-mips64.sh
shellcheck ./sys/ios-cydia.sh
shellcheck ./sys/sync.sh
shellcheck ./sys/gtk.sh
shellcheck ./sys/python.sh
shellcheck ./sys/update.sh
shellcheck ./autogen.sh
shellcheck ./binr/rax2/test-rax2.sh
shellcheck ./binr/ragg2/ragg2-cc
shellcheck ./binr/old.rarc2/rarc2-tool
shellcheck ./configure
shellcheck ./mk/rapi-list
shellcheck ./doc/repo
shellcheck ./doc/dexdump.sh
shellcheck ./configure-plugins
shellcheck ./libr/egg/t/t-fun5.sh
shellcheck ./libr/egg/t/t-fun.sh
shellcheck ./libr/egg/t/t-strlen.sh
shellcheck ./libr/egg/t/t-fun4.sh
shellcheck ./libr/egg/t/t-fun6.sh
shellcheck ./libr/egg/t/t-nest2.sh
shellcheck ./libr/egg/t/t-exit1.sh
shellcheck ./libr/egg/t/t-looptail.sh
shellcheck ./libr/egg/t/t-loop.sh
shellcheck ./libr/egg/t/t-nest3.sh
shellcheck ./libr/egg/t/t-nest.sh
shellcheck ./libr/egg/t/t-fun3.sh
shellcheck ./libr/egg/t/t-hello.sh
shellcheck ./libr/egg/t/t-fun2.sh
shellcheck ./libr/egg/t/t-loop2.sh
shellcheck ./libr/symgraph.pl
shellcheck ./libr/fs/p/makeplugin.sh
shellcheck ./libr/depgraph.pl
shellcheck ./libr/syscall/d/par.sh
shellcheck ./libr/syscall/d/gen.sh
shellcheck ./libr/stripsyms.sh
shellcheck ./libr/asm/t/test.new
shellcheck ./libr/asm/t/test.nz
shellcheck ./libr/asm/t/test.arm
shellcheck ./libr/asm/t/lops.sh
shellcheck ./libr/asm/t/test.cmp
shellcheck ./media/Radare2.iosapp/Radare2
shellcheck ./configure.hook