ifeq (${_INCLUDE_MK_CCCL_},)
_INCLUDE_MK_CCCL_=1
CC?=cccl
RANLIB=echo no ranlib for
ONELIB=0
CC_AR=arlib q ${LIBAR}
AR=arlib
EXT_AR=lib
CFLAGS+=-MD
CFLAGS_INCLUDE=-I
LDFLAGS_LINK=-l
LDFLAGS_LINKPATH=-L
CFLAGS_OPT0=-O0
CFLAGS_OPT1=-O1
CFLAGS_OPT2=-O2
CFLAGS_OPT3=-O3
CFLAGS_DEBUG=-g
PIC_CFLAGS=

LDFLAGS_LIB=${LDFLAGS} -shared
LDFLAGS_SONAME=-Wl,-soname=

CC_LIB=${CC} ${LDFLAGS_LIB} -o ${LIBSO}
endif
