ifeq (${_INCLUDE_MK_GCC_},)
_INCLUDE_MK_GCC_=1
CC=i686-pc-mingw32-gcc
RANLIB=i686-pc-mingw32-ranlib
ONELIB=0
OSTYPE=windows
LINK=
CC_AR=i686-pc-mingw32-ar -r ${LIBAR}
PICFLAGS=
CFLAGS+=${PICFLAGS} -MD -D__WINDOWS__=1
CC_LIB=${CC} -shared -o
CFLAGS_INCLUDE=-I
LDFLAGS+=-static-libgcc
LDFLAGS_LINK=-l
LDFLAGS_LINKPATH=-L
CFLAGS_OPT0=-O0
CFLAGS_OPT1=-O1
CFLAGS_OPT2=-O2
CFLAGS_OPT3=-O3
CFLAGS_DEBUG=-g
endif
