ARCH=mipsel
CROSS_ROOT=/usr/bin
CROSS_TRIPLET=${ARCH}-linux-gnu

CROSS=${CROSS_ROOT}/${CROSS_TRIPLET}-
CC=${CROSS}gcc
USERCC=${CROSS}gcc
RANLIB=${CROSS}ranlib
AR=${CROSS}ar
CC_AR=${AR} -r ${LIBAR}
PARTIALLD=${CROSS}ld -r --whole-archive

ONELIB=0
OSTYPE=gnulinux
PICFLAGS=-fPIC -fpic
CFLAGS+=${PICFLAGS}
LDFLAGS+=-ldl -pthread -lutil
CC_LIB=${CC} -shared -o
CFLAGS_INCLUDE=-I
LDFLAGS_LINK=-l
LDFLAGS_LINKPATH=-L
CFLAGS_OPT0=-O0
CFLAGS_OPT1=-O1
CFLAGS_OPT2=-O2
CFLAGS_OPT3=-O3
CFLAGS_DEBUG=-g
