ifeq (${_INCLUDE_MK_MUSL_GCC_},)
_INCLUDE_MK_GCC_=1
CC?=musl-gcc
OBJCOPY?=objcopy
RANLIB?=ranlib
ONELIB=0
AR?=ar
CC_AR=${AR} q ${LIBAR}
CFLAGS+=-MD
CFLAGS_INCLUDE=-I
LDFLAGS_LINK=-l
LDFLAGS_LINKPATH=-L
CFLAGS_OPT0=-O0
CFLAGS_OPT1=-O1
CFLAGS_OPT2=-O2
CFLAGS_OPT3=-O3
CFLAGS_DEBUG=-g
LD?=ld

PARTIALLD=${LD} -r --whole-archive
LDFLAGS_LIB=${LDFLAGS} -shared
LDFLAGS_SONAME=-Wl,-soname=

CC_LIB=${CC} ${LDFLAGS_LIB} -o ${LIBSO}
endif
