#!/bin/sh

# GPL 3+ - Copyright (C) 2016 - pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.dcu'
FILE=/bin/test
ARGS=-d
BROKEN=
IGNORE_ERR=1
CMDS='
?v $$
dcu entry0
ieq
sr PC
?v $$
'
EXPECT='0x7fff5fc01000
0x10000134c
0x10000134c
'
run_test

