#!/bin/sh

# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='asm.os'
FILE=-
ARGS=
BROKEN=
CMDS='e asm.os'
EXPECT='darwin
'
run_test

