OBJ_DUMMY=anal_dummy.o

STATIC_OBJ+=${OBJ_DUMMY}
TARGET_DUMMY=anal_dummy.${EXT_SO}

ALL_TARGETS+=${TARGET_DUMMY}

${TARGET_DUMMY}: ${OBJ_DUMMY}
	${CC} ${CFLAGS} -o ${TARGET_DUMMY} ${OBJ_DUMMY}
	@#strip -s ${TARGET_DUMMY}
