NBIND=egg_bind
OBJ_BIND=${NBIND}.o
STATIC_OBJ+=${OBJ_BIND}
TARGET_${NBIND}=${NBIND}.${EXT_SO}
CFLAGS+=-DR2_PLUGIN_INCORE

ALL_TARGETS+=${TARGET_${NBIND}}

${TARGET_BIND} ${TARGET_${NBIND}}: ${OBJ_BIND}
	${CC} $(call libname,${NBIND}) ${LDFLAGS} ${CFLAGS} -o ${TARGET_${NBIND}} ${OBJ_BIND}
