NNULLBY=egg_nullby
OBJ_NULLBY=${NNULLBY}.o
STATIC_OBJ+=${OBJ_NULLBY}
TARGET_${NNULLBY}=${NNULLBY}.${EXT_SO}
CFLAGS+=-DR2_PLUGIN_INCORE

ALL_TARGETS+=${TARGET_${NNULLBY}}

${TARGET_NULLBY} ${TARGET_${NNULLBY}}: ${OBJ_NULLBY}
	${CC} $(call libname,${NNULLBY}) ${LDFLAGS} ${CFLAGS} -o ${TARGET_${NNULLBY}} ${OBJ_NULLBY}
