NREVERSE=egg_reverse
OBJ_REVERSE=${NREVERSE}.o
STATIC_OBJ+=${OBJ_REVERSE}
TARGET_${NREVERSE}=${NREVERSE}.${EXT_SO}
CFLAGS+=-DR2_PLUGIN_INCORE

ALL_TARGETS+=${TARGET_${NREVERSE}}

${TARGET_REVERSE} ${TARGET_${NREVERSE}}: ${OBJ_REVERSE}
	${CC} $(call libname,${NREVERSE}) ${LDFLAGS} ${CFLAGS} -o ${TARGET_${NREVERSE}} ${OBJ_REVERSE}
