N=egg_x86_osx_binsh
OBJ_X86OSXBINSH=${N}.o
STATIC_OBJ+=${OBJ_X86OSXBINSH}
TARGET_${N}=${N}.${EXT_SO}

ALL_TARGETS+=${TARGET_${N}}

${TARGET_X86OSXBINSH}: ${OBJ_X86OSXBINSH}
	${CC} $(call libname,${N}) ${LDFLAGS} ${CFLAGS} -o ${TARGET_${N}} ${OBJ_X86OSXBINSH}
