include ../config.mk

NAME=r_cons
OBJS=cons.o pipe.o output.o grep.o less.o more.o pager.o utf8.o
OBJS+=line.o hud.o rgb.o input.o pal.o editor.o 2048.o
OBJS+=canvas.o canvas_line.o stiv.o
DEPS=r_util

include ../rules.mk

line.o: dietline.c
