NAME=r_core
DEPS=r_config r_cons r_line r_io r_cmd r_util r_print r_flags r_asm r_lib r_macro r_debug r_hash r_bin r_lang r_io r_asm r_anal r_config r_macro r_print

OBJ=core.o cmd.o file.o config.o visual.o io.o yank.o

include ../rules.mk
