OBJ_TMS320PSEUDO+=parse_tms320_pseudo.o

TARGET_TMS320PSEUDO=parse_tms320_pseudo.${EXT_SO}
ALL_TARGETS+=${TARGET_TMS320PSEUDO}
STATIC_OBJ+=${OBJ_TMS320PSEUDO}

ifeq ($(CC),cccl)
TMS320_CFLAGS:=${CFLAGS}
else
TMS320_CFLAGS:=${CFLAGS} ${LINK}
endif

${TARGET_TMS320PSEUDO}: ${OBJ_TMS320PSEUDO}
	${CC} $(call libname,parse_tms320_pseudo) -L../../util -llibr_util \
		$(LDFLAGS_SHARED) ${TMS320_CFLAGS} -o ${TARGET_TMS320PSEUDO} ${OBJ_TMS320PSEUDO}
