#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami appsectableW7.exe - open'
FILE=../../bins/pe/appsectableW7.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami appsectableW7.exe - entrypoint'
FILE=../../bins/pe/appsectableW7.exe
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test

NAME='PE: corkami appsectableW7.exe - pi 1'
FILE=../../bins/pe/appsectableW7.exe
CMDS='
pi 1
'
EXPECT='push 0x401018
'
IGNORE_ERR=1
run_test