#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami bigib.exe - open'
FILE=../../bins/pe/bigib.exe
ARGS=''
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test

NAME='PE: corkami bigib.exe - entrypoint'
FILE=../../bins/pe/bigib.exe
CMDS='
s
'
EXPECT='0x7efd1000
'
IGNORE_ERR=1
run_test

NAME='PE: corkami bigib.exe - pi 1'
FILE=../../bins/pe/bigib.exe
CMDS='
pi 1
'
EXPECT='push 0x7efd1018
'
IGNORE_ERR=1
run_test