#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dll-dynunicld.exe - open'
FILE=../../bins/pe/dll-dynunicld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami dll-dynunicld.exe - entrypoint'
FILE=../../bins/pe/dll-dynunicld.exe
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test

NAME='PE: corkami dll-dynunicld.exe - pi 1'
FILE=../../bins/pe/dll-dynunicld.exe
CMDS='e asm.filter=false
pi 1
'
EXPECT='push 0x40102c
'
IGNORE_ERR=1
run_test