#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllbound.dll - open'
FILE=../../bins/pe/dllbound.dll
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami dllbound.dll - entrypoint'
FILE=../../bins/pe/dllbound.dll
CMDS='
s
'
EXPECT='0x1001000
'
IGNORE_ERR=1
run_test

NAME='PE: corkami dllbound.dll - pi 1'
FILE=../../bins/pe/dllbound.dll
CMDS='e asm.filter=false
pi 1
'
EXPECT='push 1
'
IGNORE_ERR=1
run_test