#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllemptyexp-ld.exe - open'
FILE=../../bins/pe/dllemptyexp-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami dllemptyexp-ld.exe - entrypoint'
FILE=../../bins/pe/dllemptyexp-ld.exe
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test

NAME='PE: corkami dllemptyexp-ld.exe - pi 1'
FILE=../../bins/pe/dllemptyexp-ld.exe
CMDS='e asm.filter=false
pi 1
'
EXPECT='call dword [0x4010a0]
'
IGNORE_ERR=1
run_test