#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=
NAME='PE: corkami dllmaxvals.dll - open'
FILE=../../bins/pe/dllmaxvals.dll
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test
