#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami imports_multidesc.exe - open'
FILE=../../bins/pe/imports_multidesc.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
