#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami imports_tinyW7.exe - open'
IGNORE_ERR=1
FILE=../../bins/pe/imports_tinyW7.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
