#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dep.exe - open'
FILE=../../bins/pe/dep.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami dep.exe - dep not enabled'
FILE=../../bins/pe/no_dep.exe
ARGS='-n'
CMDS="!rabin2 -k 'pe.nx' ${FILE}"
EXPECT='false

'
run_test

NAME='PE: corkami dep.exe - dep not enabled'
FILE=../../bins/pe/no_dep.exe
ARGS=
CMDS="k bin/cur/pe.nx"
EXPECT='false

'

run_test
