OBJ_PTRACE=debug_ptrace.o

STATIC_OBJ+=${OBJ_PTRACE}
TARGET_PTRACE=debug_ptrace.${EXT_SO}

ALL_TARGETS+=${TARGET_PTRACE}

${TARGET_PTRACE}: ${OBJ_PTRACE}
	${CC} ${CFLAGS} -o ${TARGET_PTRACE} ${OBJ_PTRACE}
