OBJ_RV32IMA=debug_rv32ima.o

STATIC_OBJ+=${OBJ_RV32IMA}
TARGET_RV32IMA=debug_rv32ima.${EXT_SO}

ALL_TARGETS+=${TARGET_RV32IMA}

${TARGET_RV32IMA}: ${OBJ_RV32IMA}
	${CC} $(call libname,debug_rv32ima) ${OBJ_RV32IMA} ${CFLAGS} ${LDFLAGS} -o ${TARGET_RV32IMA}
