BIN=rasign2
BINDEPS=r_anal r_util r_core r_search r_main

include ../../libr/main/deps.mk
include ../rules.mk
#include ../../libr/socket/deps.mk
#include ../../shlr/zip/deps.mk
#include ../../shlr/gdb/deps.mk
#include ../../shlr/bochs/deps.mk
#include ../../shlr/qnx/deps.mk
