OBJ_CHARSET_ASCII_ANSI=muta_charset_ascii_ansi.o

STATIC_OBJ+=${OBJ_CHARSET_ASCII_ANSI}
TARGET_CHARSET_ASCII_ANSI=muta_charset_ascii_ansi.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_ASCII_ANSI}

${TARGET_CHARSET_ASCII_ANSI}: ${OBJ_CHARSET_ASCII_ANSI}
	${CC} $(call libname,muta_charset_ascii_ansi) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_ASCII_ANSI} ${OBJ_CHARSET_ASCII_ANSI}
