OBJ_CHARSET_KATAKANA=muta_charset_katakana.o

STATIC_OBJ+=${OBJ_CHARSET_KATAKANA}
TARGET_CHARSET_KATAKANA=muta_charset_katakana.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_KATAKANA}

${TARGET_CHARSET_KATAKANA}: ${OBJ_CHARSET_KATAKANA}
	${CC} $(call libname,muta_charset_katakana) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_KATAKANA} ${OBJ_CHARSET_KATAKANA}
