OBJ_CHARSET_ARABIC_WINDOWS=muta_charset_arabic_windows.o

STATIC_OBJ+=${OBJ_CHARSET_ARABIC_WINDOWS}
TARGET_CHARSET_ARABIC_WINDOWS=muta_charset_arabic_windows.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_ARABIC_WINDOWS}

${TARGET_CHARSET_ARABIC_WINDOWS}: ${OBJ_CHARSET_ARABIC_WINDOWS}
	${CC} $(call libname,muta_charset_arabic_windows) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_ARABIC_WINDOWS} ${OBJ_CHARSET_ARABIC_WINDOWS}
