OBJ_CHARSET_HEBREW_ISO=muta_charset_hebrew_iso.o

STATIC_OBJ+=${OBJ_CHARSET_HEBREW_ISO}
TARGET_CHARSET_HEBREW_ISO=muta_charset_hebrew_iso.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_HEBREW_ISO}

${TARGET_CHARSET_HEBREW_ISO}: ${OBJ_CHARSET_HEBREW_ISO}
	${CC} $(call libname,muta_charset_hebrew_iso) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_HEBREW_ISO} ${OBJ_CHARSET_HEBREW_ISO}
