OBJ_CHARSET_HIRAGANA=muta_charset_hiragana.o

STATIC_OBJ+=${OBJ_CHARSET_HIRAGANA}
TARGET_CHARSET_HIRAGANA=muta_charset_hiragana.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_HIRAGANA}

${TARGET_CHARSET_HIRAGANA}: ${OBJ_CHARSET_HIRAGANA}
	${CC} $(call libname,muta_charset_hiragana) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_HIRAGANA} ${OBJ_CHARSET_HIRAGANA}
