OBJ_CHARSET_ASCII_OEM=muta_charset_ascii_oem.o

STATIC_OBJ+=${OBJ_CHARSET_ASCII_OEM}
TARGET_CHARSET_ASCII_OEM=muta_charset_ascii_oem.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_ASCII_OEM}

${TARGET_CHARSET_ASCII_OEM}: ${OBJ_CHARSET_ASCII_OEM}
	${CC} $(call libname,muta_charset_ascii_oem) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_ASCII_OEM} ${OBJ_CHARSET_ASCII_OEM}
