OBJ_CHARSET_ASCII=muta_charset_ascii.o

STATIC_OBJ+=${OBJ_CHARSET_ASCII}
TARGET_CHARSET_ASCII=muta_charset_ascii.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_ASCII}

${TARGET_CHARSET_ASCII}: ${OBJ_CHARSET_ASCII}
	${CC} $(call libname,muta_charset_ascii) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_ASCII} ${OBJ_CHARSET_ASCII}
