OBJ_CHARSET_CYRILLIC_ISO=muta_charset_cyrillic_iso.o

STATIC_OBJ+=${OBJ_CHARSET_CYRILLIC_ISO}
TARGET_CHARSET_CYRILLIC_ISO=muta_charset_cyrillic_iso.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_CYRILLIC_ISO}

${TARGET_CHARSET_CYRILLIC_ISO}: ${OBJ_CHARSET_CYRILLIC_ISO}
	${CC} $(call libname,muta_charset_cyrillic_iso) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_CYRILLIC_ISO} ${OBJ_CHARSET_CYRILLIC_ISO}
