OBJ_CHARSET_POKERED=muta_charset_pokered.o

STATIC_OBJ+=${OBJ_CHARSET_POKERED}
TARGET_CHARSET_POKERED=muta_charset_pokered.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_POKERED}

${TARGET_CHARSET_POKERED}: ${OBJ_CHARSET_POKERED}
	${CC} $(call libname,muta_charset_pokered) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_POKERED} ${OBJ_CHARSET_POKERED}
