OBJ_CHARSET_JIS7=muta_charset_jis7.o

STATIC_OBJ+=${OBJ_CHARSET_JIS7}
TARGET_CHARSET_JIS7=muta_charset_jis7.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_JIS7}

${TARGET_CHARSET_JIS7}: ${OBJ_CHARSET_JIS7}
	${CC} $(call libname,muta_charset_jis7) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_JIS7} ${OBJ_CHARSET_JIS7}
