OBJ_CHARSET_HEBREW_WINDOWS=muta_charset_hebrew_windows.o

STATIC_OBJ+=${OBJ_CHARSET_HEBREW_WINDOWS}
TARGET_CHARSET_HEBREW_WINDOWS=muta_charset_hebrew_windows.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_HEBREW_WINDOWS}

${TARGET_CHARSET_HEBREW_WINDOWS}: ${OBJ_CHARSET_HEBREW_WINDOWS}
	${CC} $(call libname,muta_charset_hebrew_windows) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_HEBREW_WINDOWS} ${OBJ_CHARSET_HEBREW_WINDOWS}
