OBJ_CHARSET_CYRILLIC_WINDOWS=muta_charset_cyrillic_windows.o

STATIC_OBJ+=${OBJ_CHARSET_CYRILLIC_WINDOWS}
TARGET_CHARSET_CYRILLIC_WINDOWS=muta_charset_cyrillic_windows.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_CYRILLIC_WINDOWS}

${TARGET_CHARSET_CYRILLIC_WINDOWS}: ${OBJ_CHARSET_CYRILLIC_WINDOWS}
	${CC} $(call libname,muta_charset_cyrillic_windows) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_CYRILLIC_WINDOWS} ${OBJ_CHARSET_CYRILLIC_WINDOWS}
