OBJ_CHARSET_BIG5=muta_charset_big5.o

STATIC_OBJ+=${OBJ_CHARSET_BIG5}
TARGET_CHARSET_BIG5=muta_charset_big5.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_BIG5}

${TARGET_CHARSET_BIG5}: ${OBJ_CHARSET_BIG5}
	${CC} $(call libname,muta_charset_big5) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_BIG5} ${OBJ_CHARSET_BIG5}
