OBJ_CHARSET_EBCDIC37=muta_charset_ebcdic37.o

STATIC_OBJ+=${OBJ_CHARSET_EBCDIC37}
TARGET_CHARSET_EBCDIC37=muta_charset_ebcdic37.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_EBCDIC37}

${TARGET_CHARSET_EBCDIC37}: ${OBJ_CHARSET_EBCDIC37}
	${CC} $(call libname,muta_charset_ebcdic37) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_EBCDIC37} ${OBJ_CHARSET_EBCDIC37}
