OBJ_CHARSET_GREEK_WINDOWS=muta_charset_greek_windows.o

STATIC_OBJ+=${OBJ_CHARSET_GREEK_WINDOWS}
TARGET_CHARSET_GREEK_WINDOWS=muta_charset_greek_windows.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_GREEK_WINDOWS}

${TARGET_CHARSET_GREEK_WINDOWS}: ${OBJ_CHARSET_GREEK_WINDOWS}
	${CC} $(call libname,muta_charset_greek_windows) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_GREEK_WINDOWS} ${OBJ_CHARSET_GREEK_WINDOWS}
