OBJ_CHARSET_ISO_646=muta_charset_iso_646.o

STATIC_OBJ+=${OBJ_CHARSET_ISO_646}
TARGET_CHARSET_ISO_646=muta_charset_iso_646.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_ISO_646}

${TARGET_CHARSET_ISO_646}: ${OBJ_CHARSET_ISO_646}
	${CC} $(call libname,muta_charset_iso_646) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_ISO_646} ${OBJ_CHARSET_ISO_646}
