OBJ_CHARSET_ARABIC_ISO=muta_charset_arabic_iso.o

STATIC_OBJ+=${OBJ_CHARSET_ARABIC_ISO}
TARGET_CHARSET_ARABIC_ISO=muta_charset_arabic_iso.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_ARABIC_ISO}

${TARGET_CHARSET_ARABIC_ISO}: ${OBJ_CHARSET_ARABIC_ISO}
	${CC} $(call libname,muta_charset_arabic_iso) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_ARABIC_ISO} ${OBJ_CHARSET_ARABIC_ISO}
