OBJ_CHARSET_GREEK_ISO=muta_charset_greek_iso.o

STATIC_OBJ+=${OBJ_CHARSET_GREEK_ISO}
TARGET_CHARSET_GREEK_ISO=muta_charset_greek_iso.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_GREEK_ISO}

${TARGET_CHARSET_GREEK_ISO}: ${OBJ_CHARSET_GREEK_ISO}
	${CC} $(call libname,muta_charset_greek_iso) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_GREEK_ISO} ${OBJ_CHARSET_GREEK_ISO}
