OBJ_CHARSET_MACINTOSH=muta_charset_macintosh.o

STATIC_OBJ+=${OBJ_CHARSET_MACINTOSH}
TARGET_CHARSET_MACINTOSH=muta_charset_macintosh.${EXT_SO}

ALL_TARGETS+=${TARGET_CHARSET_MACINTOSH}

${TARGET_CHARSET_MACINTOSH}: ${OBJ_CHARSET_MACINTOSH}
	${CC} $(call libname,muta_charset_macintosh) ${LDFLAGS} ${CFLAGS} -o ${TARGET_CHARSET_MACINTOSH} ${OBJ_CHARSET_MACINTOSH}
