OBJ_SIMPLEHASH=muta_simplehash.o

STATIC_OBJ+=${OBJ_SIMPLEHASH}
TARGET_SIMPLEHASH=muta_simplehash.${EXT_SO}

ALL_TARGETS+=${TARGET_SIMPLEHASH}

${TARGET_SIMPLEHASH}: ${OBJ_SIMPLEHASH}
	$(CC) $(call libname,muta_simplehash) ${LDFLAGS} ${CFLAGS} -o ${TARGET_SIMPLEHASH} ${OBJ_SIMPLEHASH}
