#!/bin/sh

# GPL 3+ - Copyright (C) 2016  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='mach0 swift demangle methods'
FILE=../../bins/mach0/swift-main
ARGS=
CMDS='isq~&FooClass,method
'
EXPECT='0x1000047a0 0 FooClass.bar.method__String..init.witnesstable
0x100004788 0 FooClass.foo.method__Swift.Int..init.witnesstable
0x1000017a0 0 main.FooClass.foo.method__Swift.Int
0x100001860 0 main.FooClass.bar.method__String
'
run_test

NAME='mach0 swift-x86-64 aav'
BROKEN=
FILE=../../bins/mach0/swift-main
ARGS=
CMDS='C*~Cd?
aav
C*~Cd?
'
EXPECT='114
262
'
run_test

