#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='VSF: Rocky Horror Picture Show- open'
BROKEN=
FILE=../../bins/vsf/c128-rhps-norom.vsf
IGNORE_ERR=1
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='VSF: Rocky Horror Picture Show- detection'
BROKEN=
FILE=../../bins/vsf/c128-rhps-norom.vsf
IGNORE_ERR=1
ARGS=''
CMDS="iI~os"
EXPECT='os       C128
'
run_test

NAME='VSF: Rocky Horror Picture Show- ROMs'
BROKEN=
FILE=../../bins/vsf/c128-rhps-norom.vsf
IGNORE_ERR=1
ARGS=''
CMDS="S"
EXPECT='[00] * 0x0000008c mrwx va=0x00000000 sz=0x10000 vsz=0x10000 RAM_BANK_0
[01] . 0x0001008c mrwx va=0x00000000 sz=0x10000 vsz=0x10000 RAM_BANK_1
'
run_test
