#!/bin/sh
# GPL 3+ - Copyright (C) 2011-2015  pancake, Edd Barrett, Simon Ruderich
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## Arithmetic expressions

NAME='use after free - requires asan'
FILE=malloc://1024
ARGS=
CMDS='
0
~[[0
'
EXPECT=''
run_test

NAME='sum flags'
FILE=malloc://1024
ARGS=
CMDS='
f foo=2
f bar=4
?v bar/foo
'
EXPECT='0x2
'
run_test

NAME='div $$'
FILE=malloc://1024
ARGS=
CMDS='
?v 10/2
?v $$/2@10
'
EXPECT='0x5
0x5
'
run_test

NAME='div [0]'
FILE=malloc://1024
ARGS=
CMDS='
wv 10
?v [0]/2
?v $$/2@[0]
'
EXPECT='0x5
0x5
'
run_test

NAME='basic'
FILE=malloc://1024
ARGS=
CMDS='
?v 0x10+0x30
?v 1+3*2
?v (1+3)*2
'
EXPECT='0x40
0x7
0x8
'
run_test

BROKEN=
NAME='sum'
FILE=-
ARGS=
CMDS='
f a@3
?v a+3
?v a +3
?v a+ 3
?v 3 + 3
'
EXPECT='0x6
0x6
0x6
0x6
'
run_test

BROKEN=
NAME='binary'
FILE=-
CMDS='
?e
!rax2 Bxff3f0000fcff
!rax2 Bxff3ffcff
'
EXPECT='
111111110011111100000000000000001111110011111111b
11111111001111111111110011111111b
'
run_test
