OBJ_ADDR2LINE=bininfo_addr2line.o

TARGET_ADDR2LINE=bininfo_addr2line.so
ALL_TARGETS+=${TARGET_ADDR2LINE}
STATIC_OBJ+=${OBJ_ADDR2LINE}

${TARGET_ADDR2LINE}: ${OBJ_ADDR2LINE}
	${CC} ${CFLAGS} -o ${TARGET_ADDR2LINE} ${OBJ_ADDR2LINE}
	@#strip -s asm_x86.so
