#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
F=../../bins/java/ExCaseTableSwitch.class

NAME='java disasm crash'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 10 >/dev/null
'
EXPECT=''
run_test

NAME='java switch crash'
IGNORE_ERR=1
BROKEN=
FILE=../../bins/fuzzed/zin7a5.class
ARGS=
CMDS='e scr.null=true
pd 100
'
EXPECT=''
run_test
