OBJ_NDS32PSEUDO+=$(LIBR)/arch/p/nds32/pseudo.o

TARGET_NDS32PSEUDO=parse_nds32_pseudo.${EXT_SO}
STATIC_OBJ+=${OBJ_NDS32PSEUDO}

ifeq ($(WITHPIC),1)
ALL_TARGETS+=${TARGET_NDS32PSEUDO}
${TARGET_NDS32PSEUDO}: ${OBJ_NDS32PSEUDO}
	${CC} $(call libname,parse_nds32_pseudo) ${LIBDEPS} $(LDFLAGS) \
		$(LDFLAGS_SHARED) ${CFLAGS} -o ${TARGET_NDS32PSEUDO} ${OBJ_NDS32PSEUDO}
endif
