OBJ_PROPELLER=asm_propeller.o
OBJ_PROPELLER+=../arch/propeller/propeller_disas.o
CFLAGS+=-I../arch/propeller/

STATIC_OBJ+=${OBJ_PROPELLER}
TARGET_PROPELLER=asm_propeller.${EXT_SO}

ALL_TARGETS+=${TARGET_PROPELLER}

${TARGET_PROPELLER}: ${OBJ_PROPELLER}
	${CC} ${LDFLAGS} ${CFLAGS} -o ${TARGET_PROPELLER} ${OBJ_PROPELLER}
