OBJ_PROPELLER=asm_propeller.o
OBJ_PROPELLER+=../arch/propeller/propeller_disas.o

STATIC_OBJ+=${OBJ_PROPELLER}
TARGET_PROPELLER=asm_propeller.${EXT_SO}

ALL_TARGETS+=${TARGET_PROPELLER}

${TARGET_PROPELLER}: ${OBJ_PROPELLER}
	${CC} ${LDFLAGS} ${CFLAGS} -I../arch/propeller -o ${TARGET_PROPELLER} ${OBJ_PROPELLER}
