OBJ_S390PSEUDO+=$(LIBR)/arch/p/s390/pseudo.o

TARGET_S390PSEUDO=parse_s390_pseudo.${EXT_SO}
STATIC_OBJ+=${OBJ_S390PSEUDO}

ifeq ($(WITHPIC),1)
ALL_TARGETS+=${TARGET_S390PSEUDO}
${TARGET_S390PSEUDO}: ${OBJ_S390PSEUDO}
	${CC} $(call libname,parse_s390_pseudo) ${LIBDEPS} $(LDFLAGS) \
		$(LDFLAGS_SHARED) ${CFLAGS} -o ${TARGET_S390PSEUDO} ${OBJ_S390PSEUDO}
endif
