OBJ_SYSZCS=asm_sysz.o

include p/capstone.mk

STATIC_OBJ+=${OBJ_SYSZCS}
SHARED_OBJ+=${SHARED_SYSZCS}
TARGET_SYSZCS=asm_sysz.${EXT_SO}

ALL_TARGETS+=${TARGET_SYSZCS}

${TARGET_SYSZCS}: ${OBJ_SYSZCS}
	${CC} $(call libname,asm_sysz) ${LDFLAGS} ${CFLAGS} $(CS_LDFLAGS) \
		-o ${TARGET_SYSZCS} ${OBJ_SYSZCS} ${SHARED2_SYSZCS}
