include ../config.mk

NAME=r_search
OBJS=search.o bytepat.o strings.o aes_find.o privkey_find.o
OBJS+=regexp.o keyword.o uds.o rabin_karp.o
# OBJ+=rsakey.o
R2DEPS=r_util
CFLAGS+=-g

include ../rules.mk
