/* radare - LGPL - Copyright 2020 - thestr4ng3r */

#ifndef R2_CBM_DIS_H
#define R2_CBM_DIS_H

#include <r_util.h>

// see https://www.c64-wiki.com/wiki/BASIC_token

#define R_CBM_BASIC_TOKEN_MIN 0x80
#define R_CBM_BASIC_TOKEN_MAX 0xcb

typedef enum {
	R_CBM_BASIC_TOKEN_CMD_END        = 0x80,
	R_CBM_BASIC_TOKEN_CMD_FOR        = 0x81,
	R_CBM_BASIC_TOKEN_CMD_NEXT       = 0x82,
	R_CBM_BASIC_TOKEN_CMD_DATA       = 0x83,
	R_CBM_BASIC_TOKEN_CMD_INPUT_HASH = 0x84,
	R_CBM_BASIC_TOKEN_CMD_INPUT      = 0x85,
	R_CBM_BASIC_TOKEN_CMD_DIM        = 0x86,
	R_CBM_BASIC_TOKEN_CMD_READ       = 0x87,
	R_CBM_BASIC_TOKEN_CMD_LET        = 0x88,
	R_CBM_BASIC_TOKEN_CMD_GOTO       = 0x89,
	R_CBM_BASIC_TOKEN_CMD_RUN        = 0x8a,
	R_CBM_BASIC_TOKEN_CMD_IF         = 0x8b,
	R_CBM_BASIC_TOKEN_CMD_RESTORE    = 0x8c,
	R_CBM_BASIC_TOKEN_CMD_GOSUB      = 0x8d,
	R_CBM_BASIC_TOKEN_CMD_RETURN     = 0x8e,
	R_CBM_BASIC_TOKEN_CMD_REM        = 0x8f,
	R_CBM_BASIC_TOKEN_CMD_STOP       = 0x90,
	R_CBM_BASIC_TOKEN_CMD_ON         = 0x91,
	R_CBM_BASIC_TOKEN_CMD_WAIT       = 0x92,
	R_CBM_BASIC_TOKEN_CMD_LOAD       = 0x93,
	R_CBM_BASIC_TOKEN_CMD_SAVE       = 0x94,
	R_CBM_BASIC_TOKEN_CMD_VERIFY     = 0x95,
	R_CBM_BASIC_TOKEN_CMD_DEF        = 0x96,
	R_CBM_BASIC_TOKEN_CMD_POKE       = 0x97,
	R_CBM_BASIC_TOKEN_CMD_PRINT_HASH = 0x98,
	R_CBM_BASIC_TOKEN_CMD_PRINT      = 0x99,
	R_CBM_BASIC_TOKEN_CMD_CONT       = 0x9a,
	R_CBM_BASIC_TOKEN_CMD_LIST       = 0x9b,
	R_CBM_BASIC_TOKEN_CMD_CLR        = 0x9c,
	R_CBM_BASIC_TOKEN_CMD_CMD        = 0x9d,
	R_CBM_BASIC_TOKEN_CMD_SYS        = 0x9e,
	R_CBM_BASIC_TOKEN_CMD_OPEN       = 0x9f,
	R_CBM_BASIC_TOKEN_CMD_CLOSE      = 0xa0,
	R_CBM_BASIC_TOKEN_CMD_GET        = 0xa1,
	R_CBM_BASIC_TOKEN_CMD_NEW        = 0xa2,
	R_CBM_BASIC_TOKEN_BYWORD_TAB     = 0xa3,
	R_CBM_BASIC_TOKEN_BYWORD_TO      = 0xa4,
	R_CBM_BASIC_TOKEN_BYWORD_FN      = 0xa5,
	R_CBM_BASIC_TOKEN_BYWORD_SPC     = 0xa6,
	R_CBM_BASIC_TOKEN_BYWORD_THEN    = 0xa7,
	R_CBM_BASIC_TOKEN_BYWORD_NOT     = 0xa8,
	R_CBM_BASIC_TOKEN_BYWORD_STEP    = 0xa9,
	R_CBM_BASIC_TOKEN_OPERATOR_ADD   = 0xaa,
	R_CBM_BASIC_TOKEN_OPERATOR_SUB   = 0xab,
	R_CBM_BASIC_TOKEN_OPERATOR_MUL   = 0xac,
	R_CBM_BASIC_TOKEN_OPERATOR_DIV   = 0xad,
	R_CBM_BASIC_TOKEN_OPERATOR_POW   = 0xae,
	R_CBM_BASIC_TOKEN_OPERATOR_AND   = 0xaf,
	R_CBM_BASIC_TOKEN_OPERATOR_OR    = 0xb0,
	R_CBM_BASIC_TOKEN_OPERATOR_GT    = 0xb1,
	R_CBM_BASIC_TOKEN_OPERATOR_EQ    = 0xb2,
	R_CBM_BASIC_TOKEN_OPERATOR_LT    = 0xb3,
	R_CBM_BASIC_TOKEN_FCN_SGN        = 0xb4,
	R_CBM_BASIC_TOKEN_FCN_INT        = 0xb5,
	R_CBM_BASIC_TOKEN_FCN_ABS        = 0xb6,
	R_CBM_BASIC_TOKEN_FCN_USR        = 0xb7,
	R_CBM_BASIC_TOKEN_FCN_FRE        = 0xb8,
	R_CBM_BASIC_TOKEN_FCN_POS        = 0xb9,
	R_CBM_BASIC_TOKEN_FCN_SQR        = 0xba,
	R_CBM_BASIC_TOKEN_FCN_RND        = 0xbb,
	R_CBM_BASIC_TOKEN_FCN_LOG        = 0xbc,
	R_CBM_BASIC_TOKEN_FCN_EXP        = 0xbd,
	R_CBM_BASIC_TOKEN_FCN_COS        = 0xbe,
	R_CBM_BASIC_TOKEN_FCN_SIN        = 0xbf,
	R_CBM_BASIC_TOKEN_FCN_TAN        = 0xc0,
	R_CBM_BASIC_TOKEN_FCN_ATN        = 0xc1,
	R_CBM_BASIC_TOKEN_FCN_PEEK       = 0xc2,
	R_CBM_BASIC_TOKEN_FCN_LEN        = 0xc3,
	R_CBM_BASIC_TOKEN_FCN_STR$       = 0xc4,
	R_CBM_BASIC_TOKEN_FCN_VAL        = 0xc5,
	R_CBM_BASIC_TOKEN_FCN_ASC        = 0xc6,
	R_CBM_BASIC_TOKEN_FCN_CHR$       = 0xc7,
	R_CBM_BASIC_TOKEN_FCN_LEFT$      = 0xc8,
	R_CBM_BASIC_TOKEN_FCN_RIGHT$     = 0xc9,
	R_CBM_BASIC_TOKEN_FCN_MID$       = 0xca,
	R_CBM_BASIC_TOKEN_CMD_GO         = 0xcb
} RCBMBasicToken;

R_API size_t r_cbm_basic_disassemble(R_OUT RStrBuf *out, RBuffer *buf, bool utf8);

#endif //R2_CBM_DIS_H
