BINDEPS=r_search r_util

BINS=test${EXT_EXE} test-str${EXT_EXE} test-regexp${EXT_EXE}

include ../../rules.mk

myclean:
	rm -f test${EXT_EXE} test.o test-str${EXT_EXE} test-str.o test-regexp${EXT_EXE} test-regexp.o
