#!/bin/sh

# GPL 3+ - Copyright (C) 2013-2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='sub'
FILE=-
ARGS=
CMDS='ae 1,1,-,!,?{,1,}{,2,}'
EXPECT='1
'
run_test

NAME='cond'
FILE=-
ARGS=
CMDS='ae 1,1,==,?{,1,}{,2,}'
EXPECT='1
'
run_test

NAME='cond tail'
FILE=-
BROKEN=
ARGS=
CMDS='ae 1,1,==,?{,1,}{,2,},3'
EXPECT='3
1
'
run_test

NAME='cond neg'
FILE=-
BROKEN=
ARGS=
CMDS='ae 1,1,==,!,?{,1,}{,2,}'
EXPECT='2
'
run_test


NAME='cond neg tail'
FILE=-
BROKEN=
ARGS=
CMDS='ae 1,1,==,!,?{,1,}{,2,},3'
EXPECT='3
2
'
run_test

