CFLAGS+=-Ip/grub/include
ifeq (1,$(WITH_GPL))
OBJS+=p/grub/grubfs.o
OBJS+=p/grub/kern/device.o
OBJS+=p/grub/kern/file.o
OBJS+=p/grub/kern/env.o
OBJS+=p/grub/kern/err.o
OBJS+=p/grub/kern/time.o
OBJS+=p/grub/kern/fs.o
OBJS+=p/grub/kern/partition.o
OBJS+=p/grub/kern/disk.o
OBJS+=p/grub/kern/misc.o
OBJS+=p/grub/kern/term.o
OBJS+=p/grub/kern/mm.o
OBJS+=p/grub/partmap/sunpc.o
OBJS+=p/grub/partmap/sun.o
OBJS+=p/grub/partmap/amiga.o
OBJS+=p/grub/partmap/apple.o
OBJS+=p/grub/partmap/msdos.o
OBJS+=p/grub/partmap/gpt.o
OBJS+=p/grub/partmap/bsdlabel.o
# OBJS+=p/grub/partmap/acorn.o
OBJS+=p/grub/fs/udf.o
OBJS+=p/grub/fs/ufs.o
OBJS+=p/grub/fs/sfs.o
OBJS+=p/grub/fs/hfsplus.o
OBJS+=p/grub/fs/iso9660.o
OBJS+=p/grub/fs/ntfs.o
OBJS+=p/grub/fs/fshelp.o
OBJS+=p/grub/fs/reiserfs.o
OBJS+=p/grub/fs/tar.o
OBJS+=p/grub/fs/xfs.o
OBJS+=p/grub/fs/fb.o
OBJS+=p/grub/fs/hfs.o
OBJS+=p/grub/fs/jfs.o
# OBJS+=p/grub/fs/befs_be.o
# OBJS+=p/grub/fs/affs.o
# OBJS+=p/grub/fs/afs.o
OBJS+=p/grub/fs/fat.o
OBJS+=p/grub/fs/ext2.o
OBJS+=p/grub/fs/ntfscomp.o
OBJS+=p/grub/fs/minix.o
OBJS+=p/grub/fs/cpio.o
endif
