#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='NES: Pong - open'
BROKEN=
FILE=../../bins/nes/Pong.nes
IGNORE_ERR=1
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='NES: Pong - detection'
BROKEN=
FILE=../../bins/nes/Pong.nes
IGNORE_ERR=1
ARGS=''
CMDS="iI~os"
EXPECT='os       nes
'
run_test
