#!/bin/sh
# GPL 3+ - Copyright (C) 2016 monosource

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.trace instructions'
FILE=../../bins/elf/analysis/x86-simple
ARGS=-d
BROKEN=1
CMDS='ds
sr eip
e dbg.trace = true
2ds
"pi 1 @ `atd~:0[3]`;pi 1 @ `atd~:1[3]`"
'
EXPECT='pop ebx
mov eax, 1
'
IGNORE_ERR=1
run_test
