#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='Can set db on main'
FILE=../../bins/elf/analysis/hello-objc-linux
BROKEN=
ARGS='-d'
CMDS='db main;db~1[13];'
EXPECT="\"main\"
"
run_test

# Source: http://shell-storm.org/repo/CTF/NDH2k13-Black-Badge/crackme-v2_with_bug_fix
# regression by 4fd1e99

NAME='Code seg is sane'
FILE=../../bins/elf/analysis/hello-objc-linux
BROKEN=
ARGS='-d'
CMDS='iS~LOAD0'
EXPECT="idx=32 vaddr=0x08048000 paddr=0x00000000 sz=2848 vsz=2848 perm=m-r-x name=LOAD0
"
run_test

