OBJ_RISCV=bp_riscv.o

STATIC_OBJ+=${OBJ_RISCV}
TARGET_RISCV=bp_riscv.${EXT_SO}

ALL_TARGETS+=${TARGET_RISCV}

${TARGET_RISCV}: ${OBJ_RISCV}
	${CC} $(call libname,bp_riscv) ${CFLAGS} -o ${TARGET_RISCV} ${OBJ_RISCV}
