OBJ_FATMACHO=fs_fatmacho.o

STATIC_OBJ+=${OBJ_FATMACHO}
TARGET_FATMACHO=fs_fatmacho.${EXT_SO}

ALL_TARGETS+=${TARGET_FATMACHO}

${TARGET_FATMACHO}: ${OBJ_FATMACHO}
	${CC} $(call libname,fs_fatmacho) ${LDFLAGS} ${CFLAGS} -o ${TARGET_FATMACHO} ${OBJ_FATMACHO}
