OBJ_POSIX=fs_posix.o

STATIC_OBJ+=${OBJ_POSIX}
TARGET_POSIX=fs_posix.${EXT_SO}

ALL_TARGETS+=${TARGET_POSIX}

${TARGET_POSIX}: ${OBJ_POSIX}
	${CC} ${LDFLAGS} ${CFLAGS} -o ${TARGET_POSIX} ${OBJ_POSIX} ${EXTRA}
