# ifeq ($(R2_USE_SQSH),1)
OBJ_SQUASHFS=fs_squashfs.o
CFLAGS+=$(SQSH_CFLAGS)
EXTRA+=$(SQSH_CFLAGS)

STATIC_OBJ+=${OBJ_SQUASHFS}
#STATIC_OBJ+=${EXTRA}
TARGET_SQUASHFS=fs_squashfs.${EXT_SO}

ALL_TARGETS+=${TARGET_SQUASHFS}

${TARGET_SQUASHFS}: ${OBJ_SQUASHFS}
	${CC} $(call libname,fs_squashfs) ${LDFLAGS} ${CFLAGS} -o ${TARGET_SQUASHFS} ${OBJ_SQUASHFS} ${EXTRA}
# endif
