#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/pe/standard.exe
CMDS='aaa
afi @ sub.msvcrt.dll_printf_b2d~name

'
EXPECT='name: sub.msvcrt.dll_printf_b2d
'
run_test
