#define SEMICOLON                       1
#define FUNCTION                        2
#define LPARENT                         3
#define RPARENT                         4
#define INLINE                          5
#define VOLATILE                        6
#define STATIC                          7
#define STDCALL                         8
#define CCALL                           9
#define ATTRIBUTE                      10
#define COMMA                          11
#define STRUCT                         12
#define OBRACE                         13
#define EBRACE                         14
#define UNION                          15
#define ASTERISK                       16
#define LBRACKET                       17
#define RBRACKET                       18
#define NUMBER                         19
#define CHAR                           20
#define SHORT                          21
#define INTEGER                        22
#define LONG                           23
#define FLOAT                          24
#define DOUBLE                         25
#define VOID                           26
#define UINT8                          27
#define UINT16                         28
#define UINT32                         29
#define UINT64                         30
#define SIGNED                         31
#define UNSIGNED                       32
#define CONST                          33
#define REGISTER                       34
#define IDENTIFIER                     35
