#define SEMICOLON                       1
#define FUNCTION                        2
#define LPARENT                         3
#define RPARENT                         4
#define INLINE                          5
#define VOLATILE                        6
#define STATIC                          7
#define NAKED                           8
#define VIRTUAL                         9
#define STDCALL                        10
#define CDECL                          11
#define FASTCALL                       12
#define PASCALCALL                     13
#define WINAPI                         14
#define THISCALL                       15
#define ATTRIBUTE                      16
#define COMMA                          17
#define STRUCT                         18
#define OBRACE                         19
#define EBRACE                         20
#define UNION                          21
#define ASTERISK                       22
#define LBRACKET                       23
#define RBRACKET                       24
#define NUMBER                         25
#define CHAR                           26
#define SHORT                          27
#define INTEGER                        28
#define LONG                           29
#define FLOAT                          30
#define DOUBLE                         31
#define VOID                           32
#define UINT8                          33
#define UINT16                         34
#define UINT32                         35
#define UINT64                         36
#define SIGNED                         37
#define UNSIGNED                       38
#define CONST                          39
#define REGISTER                       40
#define IDENTIFIER                     41
