#define SEMICOLON                       1
#define FUNCTION                        2
#define LPARENT                         3
#define RPARENT                         4
#define INLINE                          5
#define VOLATILE                        6
#define STATIC                          7
#define NAKED                           8
#define VIRTUAL                         9
#define STDCALL                        10
#define CDECL                          11
#define FASTCALL                       12
#define PASCALCALL                     13
#define WINAPI                         14
#define THISCALL                       15
#define ATTRIBUTE                      16
#define COMMA                          17
#define OBRACE                         18
#define EBRACE                         19
#define STRUCT                         20
#define UNION                          21
#define ALLOCA                         22
#define AT                             23
#define ASTERISK                       24
#define LBRACKET                       25
#define RBRACKET                       26
#define NUMBER                         27
#define CHAR                           28
#define BYTE                           29
#define WORD                           30
#define DWORD                          31
#define QWORD                          32
#define SHORT                          33
#define INTEGER                        34
#define LONG                           35
#define FLOAT                          36
#define DOUBLE                         37
#define VOID                           38
#define UINT8                          39
#define UINT16                         40
#define UINT32                         41
#define UINT64                         42
#define SIGNED                         43
#define UNSIGNED                       44
#define CONST                          45
#define REGISTER                       46
#define IDENTIFIER                     47
