#ifndef WINDOWS_PROCESSOR_H
#define WINDOWS_PROCESSOR_H

#ifndef _WINNT_

#define PROCESSOR_INTEL_386			386
#define PROCESSOR_INTEL_486			486
#define PROCESSOR_INTEL_PENTIUM			586
#define PROCESSOR_INTEL_IA64			2200
#define PROCESSOR_AMD_X8664			8664
#define PROCESSOR_MIPS_R4000			4000
#define PROCESSOR_ALPHA_21064			21064
#define PROCESSOR_PPC_601			601
#define PROCESSOR_PPC_603			603
#define PROCESSOR_PPC_604			604
#define PROCESSOR_PPC_620			620
#define PROCESSOR_HITACHI_SH3			10003
#define PROCESSOR_HITACHI_SH3E			10004
#define PROCESSOR_HITACHI_SH4			10005
#define PROCESSOR_MOTOROLA_821			821
#define PROCESSOR_SHx_SH3			103
#define PROCESSOR_SHx_SH4			104
#define PROCESSOR_STRONGARM			2577
#define PROCESSOR_ARM720			0x0720
#define PROCESSOR_ARM820			0x0820
#define PROCESSOR_ARM920			0x0920
#define PROCESSOR_ARM_7TDMI			70001
#define PROCESSOR_OPTIL				0x494F

#define PROCESSOR_ARCHITECTURE_INTEL		0x0000
#define PROCESSOR_ARCHITECTURE_MIPS		0x0001
#define PROCESSOR_ARCHITECTURE_ALPHA		0x0002
#define PROCESSOR_ARCHITECTURE_PPC		0x0003
#define PROCESSOR_ARCHITECTURE_SHX		0x0004
#define PROCESSOR_ARCHITECTURE_ARM		0x0005
#define PROCESSOR_ARCHITECTURE_IA64		0x0006
#define PROCESSOR_ARCHITECTURE_ALPHA64		0x0007
#define PROCESSOR_ARCHITECTURE_MSIL		0x0008
#define PROCESSOR_ARCHITECTURE_AMD64		0x0009
#define PROCESSOR_ARCHITECTURE_IA32_ON_WIN64	0x000A
#define PROCESSOR_ARCHITECTURE_NEUTRAL		0x000B
#define PROCESSOR_ARCHITECTURE_UNKNOWN		0xFFFF

#define PF_FLOATING_POINT_PRECISION_ERRATA	0
#define PF_FLOATING_POINT_EMULATED		1
#define PF_COMPARE_EXCHANGE_DOUBLE		2
#define PF_MMX_INSTRUCTIONS_AVAILABLE		3
#define PF_PPC_MOVEMEM_64BIT_OK			4
#define PF_ALPHA_BYTE_INSTRUCTIONS		5
#define PF_XMMI_INSTRUCTIONS_AVAILABLE		6
#define PF_3DNOW_INSTRUCTIONS_AVAILABLE		7
#define PF_RDTSC_INSTRUCTION_AVAILABLE		8
#define PF_PAE_ENABLED				9
#define PF_XMMI64_INSTRUCTIONS_AVAILABLE	10
#define PF_SSE_DAZ_MODE_AVAILABLE		11
#define PF_NX_ENABLED				12
#define PF_SSE3_INSTRUCTIONS_AVAILABLE		13
#define PF_COMPARE_EXCHANGE128			14
#define PF_COMPARE64_EXCHANGE128		15
#define PF_CHANNELS_ENABLED			16
#define PF_XSAVE_ENABLED			17
#define PF_ARM_VFP_32_REGISTERS_AVAILABLE	18
#define PF_ARM_NEON_INSTRUCTIONS_AVAILABLE	19
#define PF_SECOND_LEVEL_ADDRESS_TRANSLATION	20
#define PF_VIRT_FIRMWARE_ENABLED		21
#define PF_RDWRFSGSBASE_AVAILABLE		22
#define PF_FASTFAIL_AVAILABLE			23
#define PF_ARM_DIVIDE_INSTRUCTION_AVAILABLE	24
#define PF_ARM_64BIT_LOADSTORE_ATOMIC		25
#define PF_ARM_EXTERNAL_CACHE_AVAILABLE		26
#define PF_ARM_FMAC_INSTRUCTIONS_AVAILABLE	27
#define PF_RDRAND_INSTRUCTION_AVAILABLE		28


#define XSTATE_LEGACY_FLOATING_POINT		(0)
#define XSTATE_LEGACY_SSE			(1)
#define XSTATE_GSSE				(2)
#define XSTATE_AVX				(XSTATE_GSSE)

#define XSTATE_MASK_LEGACY_FLOATING_POINT	(1ui64 << (XSTATE_LEGACY_FLOATING_POINT))
#define XSTATE_MASK_LEGACY_SSE			(1ui64 << (XSTATE_LEGACY_SSE))
#define XSTATE_MASK_LEGACY			(XSTATE_MASK_LEGACY_FLOATING_POINT | XSTATE_MASK_LEGACY_SSE)
#define XSTATE_MASK_GSSE			(1ui64 << (XSTATE_GSSE))
#define XSTATE_MASK_AVX				(XSTATE_MASK_GSSE)

#define MAXIMUM_XSTATE_FEATURES			(64)


#endif /* _WINNT_ */

#endif /* WINDOWS_PROCESSOR_H */
