name: apple

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # macOS
  macos-acr:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Packaging
      run: dist/macos/build-pkg.sh
#    - name: Building Radare2
#      run: |
#        export CFLAGS="-O2" # -Werror -Wno-unused-result -Wno-unicode -Wno-unneeded-internal-declaration"
#        sys/install.sh && make -C dist/macos
    - name: Pub
      uses: actions/upload-artifact@v2
      with:
        path: dist/macos/*.pkg
        name: macos-acr
        retention-days: 30
#   macos-acr-m1:
#     runs-on: macos-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Packaging
#       run: export CC="xcrun --sdk macosx11.1 gcc -arch arm64" ; dist/macos/build-pkg.sh
#     - name: Pub
#       uses: actions/upload-artifact@v2
#       with:
#         path: dist/macos/*.pkg
#         name: macos-acr-m1
#         retention-days: 30

  # Mobile
  ios-cydia32:
    if: contains(github.ref, 'master') || contains(github.ref, 'ci-')
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pkg-config/ldid2 with Homebrew
      run: brew install pkg-config ldid
    - name: Create cydia32 package
      run: ./sys/ios-cydia32.sh
    - name: List sys/cydia
      run: ls -lahR ./dist/cydia
    - uses: actions/upload-artifact@v2
      with:
        name: ios-cydia32
        path: ./dist/cydia/radare2/radare2-arm32_*_iphoneos-arm.deb
        retention-days: 30
  ios-cydia:
    if: contains(github.ref, 'master') || contains(github.ref, 'ci-')
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pkg-config/ldid2 with Homebrew
      run: brew install pkg-config ldid
    - name: Create cydia package
      run: ./sys/ios-cydia.sh
    - name: Create iOS SDK
      run: |
        ./sys/ios-sdk.sh
        pushd /tmp/r2ios
        zip -r /tmp/r2ios-sdk.zip *
        popd
        mv /tmp/r2ios-sdk.zip .
    - uses: actions/upload-artifact@v2
      with:
        name: ios-cydia
        path: |
          ./r2ios-sdk.zip
          ./dist/cydia/radare2*/*.deb
        retention-days: 30
