name: win-arm64-native

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  w64-arm-native:
    # Using GitHub-hosted Windows ARM64 runner
    # Available for public repos as per: https://blogs.windows.com/windowsdeveloper/2025/04/14/github-actions-now-supports-windows-on-arm-runners-for-all-public-repos/
    runs-on: windows-11-arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install meson ninja r2pipe wget --break-system-packages
    - name: Extract r2 version
      shell: bash
      run: echo "branch=`sys/version.py -n`" >> $GITHUB_OUTPUT
      id: r2v
    - name: Build with meson + ninja
      shell: pwsh
      run: |
        meson --buildtype=release --prefix=$PWD\radare2-${{ steps.r2v.outputs.branch }}-w64-arm64-native -Dc_std=c11 build
        ninja -C build -j 1
        ninja -C build install
    - name: Create zip artifact
      run: 7z a radare2-${{ steps.r2v.outputs.branch }}-w64-arm64-native.zip $PWD\radare2-${{ steps.r2v.outputs.branch }}-w64-arm64-native
    - uses: actions/upload-artifact@v4
      with:
        name: w64-arm-native
        path: radare2-${{ steps.r2v.outputs.branch }}-w64-arm64-native.zip
