BIN=ragg2
BINDEPS=r_egg r_bin r_syscall r_asm
BINDEPS+=r_io r_socket
BINDEPS+=r_lang r_parse r_anal r_reg r_flag
BINDEPS+=r_magic r_cons r_util r_search
BINDEPS+=r_core r_hash r_debug r_fs r_config r_bp r_crypto

include ../rules.mk
include ../../libr/socket/deps.mk
include ../../shlr/bochs/deps.mk
include ../../shlr/qnx/deps.mk
include ../../shlr/ar/deps.mk
